import 'package:flutter/material.dart';
import 'package:flutterapp/soriana_20castroapp/generatedlistaaceitewidget4/generated/Generated00750103912730L1Widget1.dart';
import 'package:flutterapp/soriana_20castroapp/generatedlistaaceitewidget4/generated/Generated\$5690Widget1.dart';
import 'package:flutterapp/soriana_20castroapp/generatedlistaaceitewidget4/generated/GeneratedVectorWidget99.dart';
import 'package:flutterapp/soriana_20castroapp/generatedlistaaceitewidget4/generated/GeneratedVectorWidget100.dart';
import 'package:flutterapp/soriana_20castroapp/generatedlistaaceitewidget4/generated/GeneratedAceitedeoliva750ml\$5690cuWidget1.dart';
import 'package:flutterapp/soriana_20castroapp/generatedlistaaceitewidget4/generated/GeneratedEllipsisverticalsharpWidget4.dart';
import 'package:flutterapp/soriana_20castroapp/generatedlistaaceitewidget4/generated/Generated2Widget4.dart';
import 'package:flutterapp/soriana_20castroapp/generatedlistaaceitewidget4/generated/GeneratedRectangle10Widget4.dart';

/* Component Lista aceite
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedListaaceiteWidget4 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 388.0,
      height: 128.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 388.0,
              height: 128.0,
              child: GeneratedRectangle10Widget4(),
            ),
            Positioned(
              left: 176.0,
              top: 95.43988037109375,
              right: null,
              bottom: null,
              width: 17.60011863708496,
              height: 0.6113858819007874,
              child: GeneratedVectorWidget99(),
            ),
            Positioned(
              left: 106.0,
              top: 89.0,
              right: null,
              bottom: null,
              width: 15.0,
              height: 15.0,
              child: GeneratedVectorWidget100(),
            ),
            Positioned(
              left: 43.0,
              top: 25.0,
              right: null,
              bottom: null,
              width: 226.0,
              height: 39.0,
              child: GeneratedAceitedeoliva750ml$5690cuWidget1(),
            ),
            Positioned(
              left: 25.0,
              top: 4.0,
              right: null,
              bottom: null,
              width: 36.0,
              height: 119.0,
              child: Generated00750103912730L1Widget1(),
            ),
            Positioned(
              left: 329.0,
              top: 97.0,
              right: null,
              bottom: null,
              width: 43.0,
              height: 31.0,
              child: Generated$5690Widget1(),
            ),
            Positioned(
              left: 363.0,
              top: 10.0,
              right: null,
              bottom: null,
              width: 23.0,
              height: 21.0,
              child: GeneratedEllipsisverticalsharpWidget4(),
            ),
            Positioned(
              left: 133.0,
              top: 85.0,
              right: null,
              bottom: null,
              width: 30.0,
              height: 23.0,
              child: Generated2Widget4(),
            )
          ]),
    ));
  }
}
