import 'package:flutter/material.dart';
import 'package:flutterapp/soriana_20castroapp/generatediniciowidget2/generated/Generated732071_6990439131Widget.dart';
import 'package:flutterapp/soriana_20castroapp/generatediniciowidget2/generated/GeneratedCarnesDeparWidget.dart';
import 'package:flutterapp/soriana_20castroapp/generatediniciowidget2/generated/GeneratedBuscadorWidget.dart';
import 'package:flutterapp/soriana_20castroapp/generatediniciowidget2/generated/Generated5505199001000002Widget.dart';
import 'package:flutterapp/soriana_20castroapp/generatediniciowidget2/generated/GeneratedFruyVerWidget.dart';
import 'package:flutterapp/soriana_20castroapp/generatediniciowidget2/generated/GeneratedVermasWidget.dart';
import 'package:flutterapp/soriana_20castroapp/generatediniciowidget2/generated/GeneratedRectangle7Widget.dart';
import 'package:flutterapp/soriana_20castroapp/generatediniciowidget2/generated/GeneratedGroupWidget2.dart';
import 'package:flutterapp/soriana_20castroapp/generatediniciowidget2/generated/GeneratedRectangle20Widget.dart';
import 'package:flutterapp/soriana_20castroapp/generatediniciowidget2/generated/GeneratedDepartamentosWidget2.dart';
import 'package:flutterapp/soriana_20castroapp/generatediniciowidget2/generated/GeneratedImages1Widget.dart';
import 'package:flutterapp/soriana_20castroapp/generatediniciowidget2/generated/GeneratedRectangle6Widget.dart';
import 'package:flutterapp/soriana_20castroapp/generatediniciowidget2/generated/GeneratedSorianamartesymiercolesdelcampoagosto1Widget.dart';
import 'package:flutterapp/soriana_20castroapp/generatediniciowidget2/generated/Generated576932_1107363791Widget.dart';
import 'package:flutterapp/soriana_20castroapp/generatediniciowidget2/generated/GeneratedFrame7Widget.dart';

/* Frame Inicio
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedInicioWidget2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 37.0,
                top: 839.0,
                right: null,
                bottom: null,
                width: 339.0,
                height: 57.0,
                child: GeneratedFrame7Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 222.0,
                child: GeneratedRectangle7Widget(),
              ),
              Positioned(
                left: 10.0,
                top: 159.0,
                right: null,
                bottom: null,
                width: 395.0,
                height: 52.0,
                child: GeneratedRectangle6Widget(),
              ),
              Positioned(
                left: 5.0,
                top: 155.0,
                right: null,
                bottom: null,
                width: 405.0,
                height: 60.0,
                child: GeneratedBuscadorWidget(),
              ),
              Positioned(
                left: 8.0,
                top: 35.0,
                right: null,
                bottom: null,
                width: 397.0,
                height: 96.0,
                child: GeneratedImages1Widget(),
              ),
              Positioned(
                left: 22.0,
                top: 236.0,
                right: null,
                bottom: null,
                width: 369.0,
                height: 184.0,
                child: GeneratedSorianamartesymiercolesdelcampoagosto1Widget(),
              ),
              Positioned(
                left: 10.0,
                top: 432.0,
                right: null,
                bottom: null,
                width: 159.0,
                height: 58.0,
                child: GeneratedDepartamentosWidget2(),
              ),
              Positioned(
                left: 287.0,
                top: 441.0,
                right: null,
                bottom: null,
                width: 108.0,
                height: 28.0,
                child: GeneratedRectangle20Widget(),
              ),
              Positioned(
                left: 201.0,
                top: 432.0,
                right: null,
                bottom: null,
                width: 282.0,
                height: 54.0,
                child: GeneratedVermasWidget(),
              ),
              Positioned(
                left: -30.0,
                top: 485.0,
                right: null,
                bottom: null,
                width: 316.8939514160156,
                height: 189.0,
                child: GeneratedCarnesDeparWidget(),
              ),
              Positioned(
                left: 260.0,
                top: 482.0,
                right: null,
                bottom: null,
                width: 169.0,
                height: 174.0,
                child: GeneratedFruyVerWidget(),
              ),
              Positioned(
                left: 10.0,
                top: 674.0,
                right: null,
                bottom: null,
                width: 150.0,
                height: 152.0,
                child: Generated576932_1107363791Widget(),
              ),
              Positioned(
                left: 148.0,
                top: 690.0,
                right: null,
                bottom: null,
                width: 129.0,
                height: 133.0,
                child: Generated5505199001000002Widget(),
              ),
              Positioned(
                left: 278.0,
                top: 684.0,
                right: null,
                bottom: null,
                width: 116.0,
                height: 142.0,
                child: Generated732071_6990439131Widget(),
              ),
              Positioned(
                left: 336.0,
                top: 661.0,
                right: null,
                bottom: null,
                width: 73.0,
                height: 18.0,
                child: GeneratedGroupWidget2(),
              )
            ]),
      ),
    ));
  }
}
