import 'package:flutter/material.dart';
import 'package:flutterapp/soriana_20castroapp/generatedbotonwidget1/generated/GeneratedIniciarsesionWidget1.dart';

/* Component Boton
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedBotonWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 340.0,
      height: 60.0,
      decoration: BoxDecoration(
        borderRadius: BorderRadius.circular(10.0),
      ),
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            ClipRRect(
              borderRadius: BorderRadius.circular(10.0),
              child: Container(
                color: Color.fromARGB(255, 251, 208, 208),
              ),
            ),
            Positioned(
              left: 102.0,
              top: 15.0,
              right: null,
              bottom: null,
              width: 203.0,
              height: 32.0,
              child: GeneratedIniciarsesionWidget1(),
            )
          ]),
    ));
  }
}
