import 'package:flutter/material.dart';
import 'package:flutterapp/soriana_20castroapp/generatedlistaswidget5/generated/GeneratedListaaaWidget.dart';
import 'package:flutterapp/soriana_20castroapp/generatedlistaswidget5/generated/GeneratedPechugadepollode200g\$5025cuWidget.dart';
import 'package:flutterapp/soriana_20castroapp/generatedlistaswidget5/generated/Generated2Widget2.dart';
import 'package:flutterapp/soriana_20castroapp/generatedlistaswidget5/generated/GeneratedTrashoutlineWidget1.dart';
import 'package:flutterapp/soriana_20castroapp/generatedlistaswidget5/generated/Generated318462Widget.dart';
import 'package:flutterapp/soriana_20castroapp/generatedlistaswidget5/generated/GeneratedFrame6Widget.dart';
import 'package:flutterapp/soriana_20castroapp/generatedlistaswidget5/generated/GeneratedTrashoutlineWidget3.dart';
import 'package:flutterapp/soriana_20castroapp/generatedlistaswidget5/generated/GeneratedTrashoutlineWidget.dart';
import 'package:flutterapp/soriana_20castroapp/generatedlistaswidget5/generated/GeneratedRectangle16Widget.dart';
import 'package:flutterapp/soriana_20castroapp/generatedlistaswidget5/generated/GeneratedListaaceiteWidget3.dart';
import 'package:flutterapp/soriana_20castroapp/generatedlistaswidget5/generated/GeneratedListaaceiteWidget2.dart';
import 'package:flutterapp/soriana_20castroapp/generatedlistaswidget5/generated/GeneratedPagarWidget.dart';
import 'package:flutterapp/soriana_20castroapp/generatedlistaswidget5/generated/GeneratedTotalWidget.dart';
import 'package:flutterapp/soriana_20castroapp/generatedlistaswidget5/generated/Generated318463Widget.dart';
import 'package:flutterapp/soriana_20castroapp/generatedlistaswidget5/generated/Generated3184611Widget.dart';
import 'package:flutterapp/soriana_20castroapp/generatedlistaswidget5/generated/GeneratedRectangle15Widget.dart';
import 'package:flutterapp/soriana_20castroapp/generatedlistaswidget5/generated/GeneratedBrocoli1Widget.dart';
import 'package:flutterapp/soriana_20castroapp/generatedlistaswidget5/generated/GeneratedPechugas_madera680x4451Widget.dart';
import 'package:flutterapp/soriana_20castroapp/generatedlistaswidget5/generated/GeneratedListaaceiteWidget.dart';
import 'package:flutterapp/soriana_20castroapp/generatedlistaswidget5/generated/GeneratedListaaceiteWidget1.dart';
import 'package:flutterapp/soriana_20castroapp/generatedlistaswidget5/generated/Generated\$41191Widget.dart';
import 'package:flutterapp/soriana_20castroapp/generatedlistaswidget5/generated/GeneratedTrashoutlineWidget2.dart';
import 'package:flutterapp/soriana_20castroapp/generatedlistaswidget5/generated/Generated\$41191Widget1.dart';

/* Frame Listas
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedListasWidget5 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 37.0,
                top: 839.0,
                right: null,
                bottom: null,
                width: 339.0,
                height: 57.0,
                child: GeneratedFrame6Widget(),
              ),
              Positioned(
                left: 13.0,
                top: 212.0,
                right: null,
                bottom: null,
                width: 388.0,
                height: 128.0,
                child: GeneratedListaaceiteWidget(),
              ),
              Positioned(
                left: 22.0,
                top: 238.0,
                right: null,
                bottom: null,
                width: 160.0,
                height: 85.0,
                child: Generated3184611Widget(),
              ),
              Positioned(
                left: 13.0,
                top: 357.0,
                right: null,
                bottom: null,
                width: 388.0,
                height: 128.0,
                child: GeneratedListaaceiteWidget1(),
              ),
              Positioned(
                left: 12.0,
                top: 500.0,
                right: null,
                bottom: null,
                width: 390.0,
                height: 128.0,
                child: GeneratedListaaceiteWidget2(),
              ),
              Positioned(
                left: 12.0,
                top: 77.0,
                right: null,
                bottom: null,
                width: 388.0,
                height: 128.0,
                child: GeneratedListaaceiteWidget3(),
              ),
              Positioned(
                left: 243.0,
                top: 301.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 23.0,
                child: Generated2Widget2(),
              ),
              Positioned(
                left: 236.0,
                top: 435.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 23.0,
                child: Generated318462Widget(),
              ),
              Positioned(
                left: 243.0,
                top: 585.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 23.0,
                child: Generated318463Widget(),
              ),
              Positioned(
                left: 28.0,
                top: 378.0,
                right: null,
                bottom: null,
                width: 120.0,
                height: 86.0,
                child: GeneratedPechugas_madera680x4451Widget(),
              ),
              Positioned(
                left: 177.0,
                top: 382.0,
                right: null,
                bottom: null,
                width: 145.0,
                height: 35.0,
                child: GeneratedPechugadepollode200g$5025cuWidget(),
              ),
              Positioned(
                left: 23.0,
                top: 524.0,
                right: null,
                bottom: null,
                width: 144.0,
                height: 79.0,
                child: GeneratedBrocoli1Widget(),
              ),
              Positioned(
                left: 24.222808837890625,
                top: 647.0,
                right: null,
                bottom: null,
                width: 366.0831298828125,
                height: 47.250099182128906,
                child: GeneratedRectangle15Widget(),
              ),
              Positioned(
                left: 24.222808837890625,
                top: 710.0,
                right: null,
                bottom: null,
                width: 366.0831298828125,
                height: 47.250099182128906,
                child: GeneratedRectangle16Widget(),
              ),
              Positioned(
                left: 51.0,
                top: 658.0,
                right: null,
                bottom: null,
                width: 31.0,
                height: 31.0,
                child: GeneratedTotalWidget(),
              ),
              Positioned(
                left: 308.0,
                top: 652.0,
                right: null,
                bottom: null,
                width: 89.0,
                height: 49.0,
                child: Generated$41191Widget(),
              ),
              Positioned(
                left: 40.0,
                top: 721.0,
                right: null,
                bottom: null,
                width: 33.0,
                height: 28.0,
                child: GeneratedPagarWidget(),
              ),
              Positioned(
                left: 311.0,
                top: 729.0,
                right: null,
                bottom: null,
                width: 83.0,
                height: 23.0,
                child: Generated$41191Widget1(),
              ),
              Positioned(
                left: 371.0,
                top: 528.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 21.0,
                child: GeneratedTrashoutlineWidget(),
              ),
              Positioned(
                left: 376.0,
                top: 390.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 21.0,
                child: GeneratedTrashoutlineWidget1(),
              ),
              Positioned(
                left: 376.0,
                top: 248.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 21.0,
                child: GeneratedTrashoutlineWidget2(),
              ),
              Positioned(
                left: 377.0,
                top: 108.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 21.0,
                child: GeneratedTrashoutlineWidget3(),
              ),
              Positioned(
                left: 133.0,
                top: 48.0,
                right: null,
                bottom: null,
                width: 167.0,
                height: 33.0,
                child: GeneratedListaaaWidget(),
              )
            ]),
      ),
    ));
  }
}
