import 'package:flutter/material.dart';
import 'package:flutterapp/soriana_20castroapp/generatedframe1widget/generated/GeneratedGroupWidget.dart';

/* Component Frame 1
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedFrame1Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 339.0,
      height: 57.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 339.0,
              height: 57.0,
              child: GeneratedGroupWidget(),
            )
          ]),
    ));
  }
}
