import 'package:flutter/material.dart';
import 'package:flutterapp/soriana_20castroapp/generatedmenuwidget6/generated/GeneratedMetodoWidget1.dart';
import 'package:flutterapp/soriana_20castroapp/generatedmenuwidget6/generated/GeneratedVectorWidget52.dart';
import 'package:flutterapp/soriana_20castroapp/generatedmenuwidget6/generated/GeneratedFrame8Widget.dart';
import 'package:flutterapp/soriana_20castroapp/generatedmenuwidget6/generated/GeneratedLogosorianaUber2Widget.dart';
import 'package:flutterapp/soriana_20castroapp/generatedmenuwidget6/generated/GeneratedCheckmarkcircleWidget.dart';
import 'package:flutterapp/soriana_20castroapp/generatedmenuwidget6/generated/GeneratedCheckmarkcircleWidget3.dart';
import 'package:flutterapp/soriana_20castroapp/generatedmenuwidget6/generated/GeneratedSorianazaragozaWidget.dart';
import 'package:flutterapp/soriana_20castroapp/generatedmenuwidget6/generated/Generated000011Widget.dart';
import 'package:flutterapp/soriana_20castroapp/generatedmenuwidget6/generated/GeneratedRectangle29Widget.dart';
import 'package:flutterapp/soriana_20castroapp/generatedmenuwidget6/generated/GeneratedSorianaAppWidget.dart';
import 'package:flutterapp/soriana_20castroapp/generatedmenuwidget6/generated/GeneratedEnvioWidget.dart';
import 'package:flutterapp/soriana_20castroapp/generatedmenuwidget6/generated/GeneratedCheckmarkcircleWidget2.dart';
import 'package:flutterapp/soriana_20castroapp/generatedmenuwidget6/generated/GeneratedLogosorianaUber3Widget.dart';
import 'package:flutterapp/soriana_20castroapp/generatedmenuwidget6/generated/GeneratedMetodoWidget.dart';
import 'package:flutterapp/soriana_20castroapp/generatedmenuwidget6/generated/Generated250puntosWidget.dart';
import 'package:flutterapp/soriana_20castroapp/generatedmenuwidget6/generated/GeneratedCuponsorianasoriticketsavile1Widget.dart';
import 'package:flutterapp/soriana_20castroapp/generatedmenuwidget6/generated/GeneratedRectangle28Widget.dart';
import 'package:flutterapp/soriana_20castroapp/generatedmenuwidget6/generated/GeneratedChevrondownoutlineWidget.dart';
import 'package:flutterapp/soriana_20castroapp/generatedmenuwidget6/generated/GeneratedPagoWidget.dart';
import 'package:flutterapp/soriana_20castroapp/generatedmenuwidget6/generated/GeneratedCheckmarkcircleWidget1.dart';
import 'package:flutterapp/soriana_20castroapp/generatedmenuwidget6/generated/GeneratedSorianabienvenida150920001Widget.dart';
import 'package:flutterapp/soriana_20castroapp/generatedmenuwidget6/generated/GeneratedCuponsorianasoriticketjaboneszest1Widget.dart';

/* Frame Menu
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedMenuWidget6 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 37.0,
                top: 839.0,
                right: null,
                bottom: null,
                width: 339.0,
                height: 57.0,
                child: GeneratedFrame8Widget(),
              ),
              Positioned(
                left: 32.0,
                top: 47.0,
                right: null,
                bottom: null,
                width: 349.0,
                height: 98.0,
                child: GeneratedLogosorianaUber2Widget(),
              ),
              Positioned(
                left: 32.0,
                top: 238.0,
                right: null,
                bottom: null,
                width: 349.0,
                height: 71.0,
                child: GeneratedEnvioWidget(),
              ),
              Positioned(
                left: 32.0,
                top: 316.0,
                right: null,
                bottom: null,
                width: 349.0,
                height: 71.0,
                child: GeneratedPagoWidget(),
              ),
              Positioned(
                left: 32.0,
                top: 394.0,
                right: null,
                bottom: null,
                width: 349.0,
                height: 71.0,
                child: GeneratedMetodoWidget(),
              ),
              Positioned(
                left: 32.0,
                top: 472.0,
                right: null,
                bottom: null,
                width: 349.0,
                height: 71.0,
                child: GeneratedMetodoWidget1(),
              ),
              Positioned(
                left: 32.0,
                top: 164.0,
                right: null,
                bottom: null,
                width: 349.0,
                height: 35.0,
                child: GeneratedRectangle28Widget(),
              ),
              Positioned(
                left: 48.0,
                top: 168.0,
                right: null,
                bottom: null,
                width: 119.0,
                height: 36.0,
                child: GeneratedSorianazaragozaWidget(),
              ),
              Positioned(
                left: 248.0,
                top: 161.0,
                right: null,
                bottom: null,
                width: 148.0,
                height: 41.0,
                child: GeneratedLogosorianaUber3Widget(),
              ),
              Positioned(
                left: 311.0,
                top: 256.0,
                right: null,
                bottom: null,
                width: 55.0,
                height: 55.0,
                child: GeneratedCheckmarkcircleWidget(),
              ),
              Positioned(
                left: 311.0,
                top: 332.0,
                right: null,
                bottom: null,
                width: 55.0,
                height: 55.0,
                child: GeneratedCheckmarkcircleWidget1(),
              ),
              Positioned(
                left: 311.0,
                top: 420.0,
                right: null,
                bottom: null,
                width: 55.0,
                height: 55.0,
                child: GeneratedCheckmarkcircleWidget2(),
              ),
              Positioned(
                left: 312.0,
                top: 488.0,
                right: null,
                bottom: null,
                width: 55.0,
                height: 55.0,
                child: GeneratedCheckmarkcircleWidget3(),
              ),
              Positioned(
                left: 221.0,
                top: 175.0,
                right: null,
                bottom: null,
                width: 20.0,
                height: 19.0,
                child: GeneratedChevrondownoutlineWidget(),
              ),
              Positioned(
                left: 144.0,
                top: 504.0,
                right: null,
                bottom: null,
                width: 130.0,
                height: 32.0,
                child: Generated250puntosWidget(),
              ),
              Positioned(
                left: 45.0,
                top: 561.0,
                right: null,
                bottom: null,
                width: 121.0,
                height: 153.0,
                child: GeneratedSorianabienvenida150920001Widget(),
              ),
              Positioned(
                left: 219.0,
                top: 601.0,
                right: null,
                bottom: null,
                width: 147.0,
                height: 105.0,
                child: GeneratedCuponsorianasoriticketsavile1Widget(),
              ),
              Positioned(
                left: 37.0,
                top: 725.0,
                right: null,
                bottom: null,
                width: 145.0,
                height: 104.0,
                child: Generated000011Widget(),
              ),
              Positioned(
                left: 218.0,
                top: 723.0,
                right: null,
                bottom: null,
                width: 149.0,
                height: 106.0,
                child: GeneratedCuponsorianasoriticketjaboneszest1Widget(),
              ),
              Positioned(
                left: 212.0,
                top: 560.0,
                right: null,
                bottom: null,
                width: 161.0,
                height: 24.0,
                child: GeneratedRectangle29Widget(),
              ),
              Positioned(
                left: 235.0,
                top: 557.0,
                right: null,
                bottom: null,
                width: 118.0,
                height: 32.0,
                child: GeneratedSorianaAppWidget(),
              ),
              Positioned(
                left: 351.0,
                top: 566.0,
                right: null,
                bottom: null,
                width: 9.0,
                height: 12.0,
                child: GeneratedVectorWidget52(),
              )
            ]),
      ),
    ));
  }
}
