import 'package:flutter/material.dart';
import 'package:flutterapp/soriana_20castroapp/generatedloginwidget/generated/GeneratedRegistrateycreatulistadecomprasWidget.dart';
import 'package:flutterapp/soriana_20castroapp/generatedloginwidget/generated/GeneratedBotonWidget.dart';
import 'package:flutterapp/soriana_20castroapp/generatedloginwidget/generated/GeneratedRectangle3Widget.dart';
import 'package:flutterapp/soriana_20castroapp/generatedloginwidget/generated/GeneratedInputWidget1.dart';
import 'package:flutterapp/soriana_20castroapp/generatedloginwidget/generated/Generated1200pxLogoSorianaSVG1Widget.dart';
import 'package:flutterapp/soriana_20castroapp/generatedloginwidget/generated/GeneratedBienvenidoWidget.dart';
import 'package:flutterapp/soriana_20castroapp/generatedloginwidget/generated/GeneratedInputWidget.dart';
import 'package:flutterapp/soriana_20castroapp/generatedloginwidget/generated/GeneratedRectangle1Widget.dart';
import 'package:flutterapp/soriana_20castroapp/generatedloginwidget/generated/GeneratedOlvidastetucontraseaWidget.dart';

/* Frame Login
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedLoginWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 870.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 245, 245, 245),
                ),
              ),
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: -13.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 493.0,
                child: GeneratedRectangle3Widget(),
              ),
              Positioned(
                left: 34.0,
                top: 24.0,
                right: null,
                bottom: null,
                width: 351.0,
                height: 275.0,
                child: Generated1200pxLogoSorianaSVG1Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 330.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 449.0,
                child: GeneratedRectangle1Widget(),
              ),
              Positioned(
                left: 48.0,
                top: 340.0,
                right: null,
                bottom: null,
                width: 341.0,
                height: 145.0,
                child: GeneratedBienvenidoWidget(),
              ),
              Positioned(
                left: 80.0,
                top: 453.0,
                right: null,
                bottom: null,
                width: 277.0,
                height: 29.0,
                child: GeneratedRegistrateycreatulistadecomprasWidget(),
              ),
              Positioned(
                left: 45.0,
                top: 506.0,
                right: null,
                bottom: null,
                width: 340.0,
                height: 60.0,
                child: GeneratedInputWidget(),
              ),
              Positioned(
                left: 45.0,
                top: 592.0,
                right: null,
                bottom: null,
                width: 340.0,
                height: 60.0,
                child: GeneratedInputWidget1(),
              ),
              Positioned(
                left: 51.0,
                top: 663.0,
                right: null,
                bottom: null,
                width: 212.0,
                height: 33.0,
                child: GeneratedOlvidastetucontraseaWidget(),
              ),
              Positioned(
                left: 45.0,
                top: 705.0,
                right: null,
                bottom: null,
                width: 340.0,
                height: 60.0,
                child: GeneratedBotonWidget(),
              )
            ]),
      ),
    ));
  }
}
