import 'package:flutter/material.dart';

/* Frame remove
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedRemoveWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 87.0,
        height: 64.0,
      ),
    ));
  }
}
