import 'package:flutter/material.dart';
import 'package:flutterapp/soriana_20castroapp/generatedinputwidget2/generated/GeneratedRectangle2Widget2.dart';
import 'package:flutterapp/soriana_20castroapp/generatedinputwidget2/generated/GeneratedCorreoelectronicoWidget2.dart';

/* Component Input
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedInputWidget2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 340.0,
      height: 60.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 340.0,
              height: 60.0,
              child: GeneratedRectangle2Widget2(),
            ),
            Positioned(
              left: 33.0,
              top: 13.0,
              right: null,
              bottom: null,
              width: 122.0,
              height: 37.0,
              child: GeneratedCorreoelectronicoWidget2(),
            )
          ]),
    ));
  }
}
