import 'package:flutter/material.dart';
import 'package:flutterapp/soriana_20castroapp/generatedperfilwidget8/generated/GeneratedSorianatarjetacreditoe15302678952891Widget.dart';
import 'package:flutterapp/soriana_20castroapp/generatedperfilwidget8/generated/GeneratedInicasesionparatenerunamejorexperienciaenlaappdesoriana.dart';
import 'package:flutterapp/soriana_20castroapp/generatedperfilwidget8/generated/GeneratedFrame4Widget.dart';
import 'package:flutterapp/soriana_20castroapp/generatedperfilwidget8/generated/GeneratedJULIOESREGALADOWidget.dart';
import 'package:flutterapp/soriana_20castroapp/generatedperfilwidget8/generated/GeneratedCreaunalistaconlosproductosdetupreferenciWidget.dart';
import 'package:flutterapp/soriana_20castroapp/generatedperfilwidget8/generated/GeneratedChecklist41335_960_7201Widget.dart';
import 'package:flutterapp/soriana_20castroapp/generatedperfilwidget8/generated/GeneratedRealizatufacturayconsultaelestadodetuspedidosWidget.dart';
import 'package:flutterapp/soriana_20castroapp/generatedperfilwidget8/generated/GeneratedDisfrutaderecompensasyacumulapuntosWidget.dart';
import 'package:flutterapp/soriana_20castroapp/generatedperfilwidget8/generated/GeneratedRegistrarWidget.dart';
import 'package:flutterapp/soriana_20castroapp/generatedperfilwidget8/generated/GeneratedLogosorianaUber1Widget.dart';
import 'package:flutterapp/soriana_20castroapp/generatedperfilwidget8/generated/GeneratedIniciarsesiWidget.dart';
import 'package:flutterapp/soriana_20castroapp/generatedperfilwidget8/generated/GeneratedContenidofactura1Widget.dart';

/* Frame Perfil
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedPerfilWidget8 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 37.0,
                top: 839.0,
                right: null,
                bottom: null,
                width: 339.0,
                height: 57.0,
                child: GeneratedFrame4Widget(),
              ),
              Positioned(
                left: 32.0,
                top: 298.0,
                right: null,
                bottom: null,
                width: 350.0,
                height: 49.0,
                child: GeneratedIniciarsesiWidget(),
              ),
              Positioned(
                left: 32.0,
                top: 354.0,
                right: null,
                bottom: null,
                width: 350.0,
                height: 49.0,
                child: GeneratedRegistrarWidget(),
              ),
              Positioned(
                left: 30.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 346.0,
                height: 168.0,
                child: GeneratedLogosorianaUber1Widget(),
              ),
              Positioned(
                left: 49.0,
                top: 128.0,
                right: null,
                bottom: null,
                width: 318.0,
                height: 34.0,
                child: GeneratedJULIOESREGALADOWidget(),
              ),
              Positioned(
                left: 18.0,
                top: 194.0,
                right: null,
                bottom: null,
                width: 372.0,
                height: 99.0,
                child:
                    GeneratedInicasesionparatenerunamejorexperienciaenlaappdesoriana(),
              ),
              Positioned(
                left: 71.0,
                top: 433.0,
                right: null,
                bottom: null,
                width: 274.0,
                height: 82.0,
                child:
                    GeneratedCreaunalistaconlosproductosdetupreferenciWidget(),
              ),
              Positioned(
                left: 93.0,
                top: 547.0,
                right: null,
                bottom: null,
                width: 222.0,
                height: 85.0,
                child: GeneratedDisfrutaderecompensasyacumulapuntosWidget(),
              ),
              Positioned(
                left: 98.0,
                top: 664.0,
                right: null,
                bottom: null,
                width: 212.0,
                height: 134.0,
                child:
                    GeneratedRealizatufacturayconsultaelestadodetuspedidosWidget(),
              ),
              Positioned(
                left: 24.0,
                top: 455.0,
                right: null,
                bottom: null,
                width: 49.0,
                height: 58.0,
                child: GeneratedChecklist41335_960_7201Widget(),
              ),
              Positioned(
                left: 31.0,
                top: 598.197265625,
                right: null,
                bottom: null,
                width: 76.0,
                height: 46.0,
                child: GeneratedSorianatarjetacreditoe15302678952891Widget(),
              ),
              Positioned(
                left: 37.87836837768555,
                top: 709.4066772460938,
                right: null,
                bottom: null,
                width: 53.0,
                height: 51.0,
                child: GeneratedContenidofactura1Widget(),
              )
            ]),
      ),
    ));
  }
}
