import 'package:flutter/material.dart';
import 'package:flutterapp/soriana_20castroapp/generateddepartamentoswidget3/generated/GeneratedGroupWidget6.dart';
import 'package:flutterapp/soriana_20castroapp/generateddepartamentoswidget3/generated/GeneratedRectangle19Widget.dart';
import 'package:flutterapp/soriana_20castroapp/generateddepartamentoswidget3/generated/GeneratedFruyVerWidget1.dart';
import 'package:flutterapp/soriana_20castroapp/generateddepartamentoswidget3/generated/GeneratedFriturasWidget.dart';
import 'package:flutterapp/soriana_20castroapp/generateddepartamentoswidget3/generated/GeneratedGroupWidget5.dart';
import 'package:flutterapp/soriana_20castroapp/generateddepartamentoswidget3/generated/GeneratedGroupWidget4.dart';
import 'package:flutterapp/soriana_20castroapp/generateddepartamentoswidget3/generated/Generated0321_Detergentes_Persil_41Widget.dart';
import 'package:flutterapp/soriana_20castroapp/generateddepartamentoswidget3/generated/GeneratedDepartamentosWidget5.dart';
import 'package:flutterapp/soriana_20castroapp/generateddepartamentoswidget3/generated/GeneratedImages2Widget.dart';
import 'package:flutterapp/soriana_20castroapp/generateddepartamentoswidget3/generated/GeneratedCarnesDeparWidget1.dart';
import 'package:flutterapp/soriana_20castroapp/generateddepartamentoswidget3/generated/GeneratedCerealesWidget.dart';
import 'package:flutterapp/soriana_20castroapp/generateddepartamentoswidget3/generated/GeneratedGroupWidget7.dart';
import 'package:flutterapp/soriana_20castroapp/generateddepartamentoswidget3/generated/GeneratedFrame2Widget.dart';

/* Frame Departamentos 
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedDepartamentosWidget3 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 37.0,
                top: 839.0,
                right: null,
                bottom: null,
                width: 339.0,
                height: 57.0,
                child: GeneratedFrame2Widget(),
              ),
              Positioned(
                left: -22.0,
                top: 160.0,
                right: null,
                bottom: null,
                width: 316.8939514160156,
                height: 189.0,
                child: GeneratedCarnesDeparWidget1(),
              ),
              Positioned(
                left: 24.0,
                top: 349.0,
                right: null,
                bottom: null,
                width: 169.0,
                height: 174.0,
                child: GeneratedFruyVerWidget1(),
              ),
              Positioned(
                left: 80.0,
                top: 65.0,
                right: null,
                bottom: null,
                width: 248.0,
                height: 51.0,
                child: GeneratedRectangle19Widget(),
              ),
              Positioned(
                left: 152.0,
                top: 73.0,
                right: null,
                bottom: null,
                width: 108.0,
                height: 40.0,
                child: GeneratedDepartamentosWidget5(),
              ),
              Positioned(
                left: 13.0,
                top: 135.0,
                right: null,
                bottom: null,
                width: 73.0,
                height: 18.0,
                child: GeneratedGroupWidget4(),
              ),
              Positioned(
                left: 8.0,
                top: 346.0,
                right: null,
                bottom: null,
                width: 73.0,
                height: 18.0,
                child: GeneratedGroupWidget5(),
              ),
              Positioned(
                left: 8.0,
                top: 530.0,
                right: null,
                bottom: null,
                width: 73.0,
                height: 18.0,
                child: GeneratedGroupWidget6(),
              ),
              Positioned(
                left: 52.0,
                top: 705.0,
                right: null,
                bottom: null,
                width: 73.0,
                height: 18.0,
                child: GeneratedGroupWidget7(),
              ),
              Positioned(
                left: 20.0,
                top: 555.0,
                right: null,
                bottom: null,
                width: 203.0,
                height: 143.0,
                child: GeneratedCerealesWidget(),
              ),
              Positioned(
                left: 132.0,
                top: 690.0,
                right: null,
                bottom: null,
                width: 188.0,
                height: 154.0,
                child: GeneratedFriturasWidget(),
              ),
              Positioned(
                left: 223.0,
                top: 279.0,
                right: null,
                bottom: null,
                width: 191.0,
                height: 146.0,
                child: GeneratedImages2Widget(),
              ),
              Positioned(
                left: 253.0,
                top: 430.0,
                right: null,
                bottom: null,
                width: 150.0,
                height: 226.0,
                child: Generated0321_Detergentes_Persil_41Widget(),
              )
            ]),
      ),
    ));
  }
}
